name: s4cmb-docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["julienpeloton/s4cmb:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile sources and install
      run: |
        make
    - name: Unit tests
      run: |
        ./coverage_and_test.sh
    - name: Integration tests
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python examples/test/simple_app.py -inifile examples/inifiles/simple_parameters.py -tag 'test'
    - name: Coverage
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
