name: s4cmb

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["julienpeloton/s4cmb:latest"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Unit tests
      run: |
        pip install coverage
        ./coverage_and_test.sh
    - name: Integration tests
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python examples/test/simple_app.py -inifile examples/inifiles/simple_parameters.py -tag 'test'
    - name: Coverage
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
